name: CombatTag
version: 4.4
author: cheddar262
main: com.trc202.CombatTag.CombatTag
commands:
  CombatTag:
    description: Shows the current remaining time in a tag
    aliases: ct
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - shows you the remaining tag duration